services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - bank-data:/var/lib/postgresql/data
    networks:
      - bank-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-tasya-app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - bank-network

volumes:
  bank-data:
networks:
  bank-network:

